# LAB NO : 1

**TASK : 1**

Write a Python program that multiplies a TensorFlow tensor by a scalar value and prints the result.

In [2]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

# Create a TensorFlow tensor
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

# Define a scalar value
scalar = 2

# Multiply the tensor by the scalar
result = tensor * scalar

# Start a TensorFlow session
sess = tf.compat.v1.Session()
ts = sess.run(tensor)
result_value = sess.run(result)

# Print the results
print("Original Tensor:\n",ts)
print("\nScalar Value: ", scalar)
print("\nResult of multiplying the tensor by the scalar:")
print(result_value)
sess.close()


Original Tensor:
 [[1 2 3]
 [4 5 6]]

Scalar Value:  2

Result of multiplying the tensor by the scalar:
[[ 2  4  6]
 [ 8 10 12]]


---------------------------------------------------------------------------------------------------------------------------------

**TASK : 2**

Write a Python program that uses TensorFlow to compute the dot product of two vectors (1-D tensors).

In [3]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

vector1 = tf.constant([12, 22])
vector2 = tf.constant([21, 44])
dot_product = tf.tensordot(vector1,vector2 , axes = 1)

# Start a TensorFlow session
sess = tf.compat.v1.Session()
V1 = sess.run(vector1)
V2 = sess.run(vector2)
result = sess.run(dot_product)

# Print the result
print("Vector 1: ", V1 )
print("\nVector 2: ", V2)
print("\nRESULT : ",result)
sess.close()

Vector 1:  [12 22]

Vector 2:  [21 44]

RESULT :  1220


---------------------------------------------------------------------------------------------------------------------------------

**TASK : 3**

Write a TensorFlow program that creates two matrices, matrix1 and matrix2, with the following values:matrix1 = [ [1, 2] , [3, 4] ] matrix2 = [ [5, 6] , [7, 8] ]  
Perform the arithematic operations on these matric.

In [5]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

matrix1 = tf.constant([[1, 2],
                      [3, 4]])

matrix2 = tf.constant([[5, 6],
                      [7, 8]])

# Arithmetic Operations
addition = matrix1 + matrix2
subtraction = matrix2 - matrix1
multiplication = matrix1 * matrix2
division = matrix2 / matrix1
matrix_multiplication = tf.matmul(matrix1, matrix2)

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
addition_result = sess.run(addition)
subtraction_result = sess.run(subtraction)
multiplication_result = sess.run(multiplication)
division_result = sess.run(division)
matrix_multiplication_result = sess.run(matrix_multiplication)

# Print the results
print("Addition Result:")
print(addition_result)

print("\nSubtraction Result:")
print(subtraction_result)

print("\nMultiplication Result:")
print(multiplication_result)

print("\nDivision Result:")
print(division_result)

print("\nMatrix Multiplication Of Matrix1 And Matrix2:")
print(matrix_multiplication_result)
sess.close()

Addition Result:
[[ 6  8]
 [10 12]]

Subtraction Result:
[[4 4]
 [4 4]]

Multiplication Result:
[[ 5 12]
 [21 32]]

Division Result:
[[5.         3.        ]
 [2.33333333 2.        ]]

Matrix Multiplication Of Matrix1 And Matrix2:
[[19 22]
 [43 50]]


---------------------------------------------------------------------------------------------------------------------------------

# EXERCISES :

**1.** Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [6]:
import tensorflow as tf

# Create a vector
vector = tf.constant([1, 2, 3, 4])

# Create a scalar
scalar = tf.constant(10)

# Create a matrix
matrix = tf.constant([[1, 2],
                      [3, 4]])

# Create a tensor
tensor = tf.constant([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
v= sess.run(vector)
s= sess.run(scalar)
m= sess.run(matrix )
t= sess.run(tensor)

# Print the results
print("Vector:\n",v)
print("\nScalar:\n",s)
print("\nMatrix:\n",m)
print("\nTensor:\n",t)
sess.close()

Vector:
 [1 2 3 4]

Scalar:
 10

Matrix:
 [[1 2]
 [3 4]]

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---------------------------------------------------------------------------------------------------------------------------------

**2.** Find the shape, rank and size of the tensors you created in 1.

In [7]:
# Start a TensorFlow session
sess = tf.compat.v1.Session()

vector_shape = sess.run(tf.shape(vector))
scalar_shape = sess.run(tf.shape(scalar))
matrix_shape = sess.run(tf.shape(matrix))
tensor_shape = sess.run(tf.shape(tensor))

vector_rank = sess.run(tf.rank(vector))
scalar_rank = sess.run(tf.rank(scalar))
matrix_rank = sess.run(tf.rank(matrix))
tensor_rank = sess.run(tf.rank(tensor))

vector_size = sess.run(tf.size(vector))
scalar_size = sess.run(tf.size(scalar))
matrix_size = sess.run(tf.size(matrix))
tensor_size = sess.run(tf.size(tensor))

# Print the results
print("Vector:")
print("Shape:", vector_shape, "Rank:", vector_rank, "Size:", vector_size)

print("\nScalar:")
print("Shape:", scalar_shape, "Rank:", scalar_rank, "Size:", scalar_size)

print("\nMatrix:")
print("Shape:", matrix_shape, "Rank:", matrix_rank, "Size:", matrix_size)

print("\nTensor:")
print("Shape:", tensor_shape, "Rank:", tensor_rank, "Size:", tensor_size)

Vector:
Shape: [4] Rank: 1 Size: 4

Scalar:
Shape: [] Rank: 0 Size: 1

Matrix:
Shape: [2 2] Rank: 2 Size: 4

Tensor:
Shape: [2 2 2] Rank: 3 Size: 8


---------------------------------------------------------------------------------------------------------------------------------

**3.** Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [8]:
import tensorflow as tf

# Create two tensors with random values between 0 and 1 with shape [5, 300]
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
result1 = sess.run(tensor1)
result2 = sess.run(tensor2)

# Print the tensors
print("Tensor 1:\n", result1)
print("\nTensor 2:\n", result2)
sess.close()

Tensor 1:
 [[0.0149107  0.4715321  0.99932134 ... 0.18874669 0.4962088  0.0170511 ]
 [0.09493279 0.10225356 0.70262766 ... 0.5600767  0.28828442 0.59925866]
 [0.31643188 0.12736166 0.02176857 ... 0.8051386  0.10090053 0.17182946]
 [0.9761919  0.64838755 0.75256705 ... 0.89367247 0.20059359 0.38050032]
 [0.7714735  0.11930215 0.6817601  ... 0.7625855  0.19165719 0.2989601 ]]

Tensor 2:
 [[0.02309167 0.3243382  0.08807898 ... 0.12075603 0.22073293 0.41373146]
 [0.5056913  0.8086283  0.25928545 ... 0.65577686 0.5655227  0.26233506]
 [0.89596605 0.77796495 0.98977995 ... 0.88128734 0.63846135 0.6020353 ]
 [0.24475276 0.53788304 0.5423398  ... 0.29045486 0.34470844 0.13550854]
 [0.89808214 0.03106737 0.74504876 ... 0.28358912 0.15359223 0.97323763]]


---------------------------------------------------------------------------------------------------------------------------------

**4.** Multiply the two tensors you created in 3 using matrix multiplication.

In [9]:
# Perform matrix multiplication
matrix_mult = tf.matmul(tensor1, tf.transpose(tensor2))

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
result = sess.run(matrix_mult)

# Print the result
print("Matrix Multiplication Result:\n",result)
sess.close()

Matrix Multiplication Result:
 [[75.44998  79.838875 77.23092  73.9727   77.42517 ]
 [73.41982  76.721375 74.5135   73.57299  77.72446 ]
 [70.65619  79.62358  74.63487  72.216415 77.93402 ]
 [75.12364  81.389244 78.42085  73.05148  81.025566]
 [71.332275 77.79223  77.18885  72.953995 80.58328 ]]


---------------------------------------------------------------------------------------------------------------------------------

**5.** Multiply the two tensors you created in 3 using dot product.

In [10]:
# Perform matrix multiplication
dot_product = tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
result = sess.run(dot_product)

# Print the result
print("Dot Product Result:\n",result)
sess.close()

Dot Product Result:
 [[74.79193  74.391556 70.33914  76.49432  76.674164]
 [70.38854  70.53273  68.38504  75.01966  76.568405]
 [76.785225 73.008484 71.274765 80.434296 75.55663 ]
 [75.883835 73.30353  74.814476 78.74857  78.64054 ]
 [74.48733  75.0188   74.01694  80.440704 76.473305]]


---------------------------------------------------------------------------------------------------------------------------------

**6.** Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [11]:
import tensorflow as tf

# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
result = sess.run(tensor)

# Print the tensor and its shape
print("Tensor :\n", result)
print("\nSHAPE :",tensor.shape)
sess.close()

Tensor :
 [[[0.25568092 0.7378932  0.7120693 ]
  [0.9547168  0.5740689  0.08819008]
  [0.9259753  0.19192767 0.25912225]
  ...
  [0.759323   0.3917942  0.20224047]
  [0.23933792 0.45667183 0.6750109 ]
  [0.36575866 0.33761287 0.46965706]]

 [[0.90212774 0.24387848 0.91751254]
  [0.8428438  0.04628015 0.63519955]
  [0.932122   0.72838295 0.9284915 ]
  ...
  [0.926178   0.46627128 0.580248  ]
  [0.15691209 0.7168424  0.90761626]
  [0.17132378 0.96410954 0.07150114]]

 [[0.34630382 0.8205166  0.08539379]
  [0.9736761  0.8020495  0.34418118]
  [0.43942368 0.14248478 0.2601794 ]
  ...
  [0.22716808 0.04939258 0.3161434 ]
  [0.38105047 0.79856765 0.96620464]
  [0.33779013 0.05147731 0.12054014]]

 ...

 [[0.96664095 0.37847054 0.8502122 ]
  [0.6589228  0.0311352  0.43895423]
  [0.7364602  0.19554603 0.10694444]
  ...
  [0.12254047 0.79426587 0.2113694 ]
  [0.8887993  0.54738474 0.98495114]
  [0.44891763 0.7254982  0.69275177]]

 [[0.02975214 0.29332078 0.61873925]
  [0.10099661 0.75731826 0.

---------------------------------------------------------------------------------------------------------------------------------

**7.** Find the min and max values of the tensor you created in 6.

In [12]:
min_value = tf.reduce_min(tensor)
max_value = tf.reduce_max(tensor)

# Start a TensorFlow session
sess = tf.compat.v1.Session() 
min_result, max_result = sess.run([min_value, max_value ])

# Print the minimum and maximum values
print("Minimum Value:\n", min_result)
print("\nMaximum Value:\n", max_result)
sess.close()

Minimum Value:
 9.894371e-06

Maximum Value:
 0.99999905


---------------------------------------------------------------------------------------------------------------------------------

**8.** Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [13]:
import tensorflow as tf

tensor = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1, dtype=tf.float32)
squeezed_tensor = tf.squeeze(tensor)

print("Original Tensor Shape:", tensor.shape)
print("Squeezed Tensor Shape:", squeezed_tensor.shape)

Original Tensor Shape: (1, 224, 224, 3)
Squeezed Tensor Shape: (224, 224, 3)


---------------------------------------------------------------------------------------------------------------------------------

**9.** Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [14]:
import tensorflow as tf

# Create a tensor with shape [10] using your own choice of values
tensor = tf.constant([5, 10, 15, 20, 50, 60, 25, 30, 35, 40])

# Find the index which has the maximum value
max_index = tf.argmax(tensor)

# Start a TensorFlow session
sess = tf.compat.v1.Session()
Value = sess.run(max_index)

# Print the index of the maximum value
print("Index with Maximum Value:", Value)
sess.close()

Index with Maximum Value: 5


---------------------------------------------------------------------------------------------------------------------------------

**10.** One-hot encode the tensor you created in 9.

In [16]:
max_value = tf.reduce_max(tensor)
sess = tf.compat.v1.Session()
one_hot_encoded = tf.one_hot(tensor, depth=max_value+1)
one_hot_encoded_result = sess.run(one_hot_encoded)
print("One-hot encoded tensor:\n",one_hot_encoded_result)

One-hot encoded tensor:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.